CREATE TABLE IF NOT EXISTS players(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    elo INTEGER NOT NULL,
    num_fights INTEGER
);

CREATE TABLE IF NOT EXISTS matches(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    p1 INTEGER NOT NULL,
    p2 INTEGER NOT NULL,
    winner INTEGER,
    p1_pot INTEGER,
    p2_pot INTEGER,
    FOREIGN KEY (p1) REFERENCES players(id),
    FOREIGN KEY (p2) REFERENCES players(id),
    FOREIGN KEY (winner) REFERENCES players(id)
);

PRAGMA foreign_keys = ON;